DROP SCHEMA IF EXISTS Auto_Theft;
CREATE SCHEMA Auto_Theft;

USE Auto_Theft;

CREATE TABLE VEHICLE
    (VIN VARCHAR(50) NOT NULL,
     Make VARCHAR(50) NOT NULL,
     PRICE FLOAT NOT NULL,
     Purchase_Method VARCHAR(50) NOT NULL,
     PRIMARY KEY (VIN));

CREATE TABLE INSURANCE
    (Policy_Number INT NOT NULL,
     VIN VARCHAR(50) NOT NULL,
     Payment_Amount FLOAT NOT NULL,
     PRIMARY KEY(Policy_Number),
     FOREIGN KEY(VIN) REFERENCES VEHICLE(VIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

CREATE TABLE EVENT 
    (Event_Code INT NOT NULL, 
     Outcome VARCHAR(50) NOT NULL, 
     Year INT NOT NULL CHECK(Year >= 2000), 
     Month INT NOT NULL CHECK(Month <= 12 AND Month >= 1), 
     Day INT NOT NULL CHECK(Day <= 31 AND Day >= 1),
     Hour INT NOT NULL CHECK(Hour <= 24 AND Hour >= 0), 
     Neighbourhood VARCHAR(50) NOT NULL,
     PRIMARY KEY(Event_Code));

CREATE TABLE GOT_STOLEN 
    (Event_Code INT NOT NULL, 
     VIN VARCHAR(50) NOT NULL, 
     PRIMARY KEY (Event_Code, VIN),
     FOREIGN KEY (Event_Code) REFERENCES EVENT(Event_Code)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
     FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

CREATE TABLE HUMAN
    (SIN INT NOT NULL, 
     Birth_date DATE NOT NULL, 
     FName VARCHAR(50) NOT NULL,
     LName VARCHAR(50) NOT NULL,
     Phone INT NOT NULL,
     Email VARCHAR(50),
     PRIMARY KEY (SIN));

CREATE TABLE OWNER
    (SIN INT NOT NULL, 
     Salary_group INT NOT NULL, 
     PRIMARY KEY (SIN),
     FOREIGN KEY (SIN) REFERENCES HUMAN(SIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

CREATE TABLE OWN 
    (SIN INT NOT NULL, 
     VIN VARCHAR(50) NOT NULL, 
     PRIMARY KEY (SIN, VIN),
     FOREIGN KEY (SIN) REFERENCES OWNER(SIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
     FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

CREATE TABLE DEPARTMENT
    (Dept_ID INT NOT NULL, 
     Dname VARCHAR(50) NOT NULL, 
     PRIMARY KEY (Dept_ID));

CREATE TABLE POLICE_OFFICER
    (SIN INT NOT NULL, 
     Department INT NOT NULL, 
     PRIMARY KEY (SIN),
     FOREIGN KEY (Department) REFERENCES DEPARTMENT(Dept_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
     FOREIGN KEY (SIN) REFERENCES HUMAN(SIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE);

CREATE TABLE HANDLED
    (Police_SIN INT NOT NULL, 
     Event_Code INT NOT NULL, 
     PRIMARY KEY (Police_SIN, Event_Code),
     FOREIGN KEY (Police_SIN) REFERENCES POLICE_OFFICER(SIN)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
     FOREIGN KEY (Event_Code) REFERENCES EVENT(Event_Code)
        ON DELETE CASCADE
        ON UPDATE CASCADE);
