SELECT 
    POLICE_OFFICER.*,
    EVENT.*
FROM 
    POLICE_OFFICER
LEFT JOIN 
    HANDLED ON POLICE_OFFICER.SIN = HANDLED.Police_SIN 
LEFT JOIN 
    EVENT ON HANDLED.Event_Code = EVENT.Event_Code
GROUP BY 
    POLICE_OFFICER.SIN;
