SELECT 
    VEHICLE.Make, 
    INSURANCE.Payment_Amount,
    SUM(INSURANCE.Payment_Amount) OVER (PARTITION BY VEHICLE.Make) AS insurance_payment_by_make
FROM 
    INSURANCE
JOIN 
    VEHICLE ON INSURANCE.VIN = VEHICLE.VIN;
